import { Button } from "@/components/BaseComponents/Button/Button";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";

export default function LoginPage() {
  const router = useRouter();
  const session = useSession();

  if (session.status === "authenticated" && router.pathname === "/login") {
    router.push("/");
  }

  return (
    <>
      <Head>
        <title>login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full w-full flex-col items-center justify-center gap-10">
        LOGIN PAGE
        <Button
          type="button"
          text="Zaloguj"
          onClick={() => signIn("google", { callbackUrl: "/" })}
        />
      </main>
    </>
  );
}
