import { Button } from "@/components/BaseComponents/Button/Button";
import { signIn } from "next-auth/react";
import Head from "next/head";

export default function LoginPage() {
  return (
    <>
      <Head>
        <title>login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full w-full flex-col items-center justify-center gap-10">
        LOGIN PAGE
        <Button
          type="button"
          text="Zaloguj"
          onClick={() => signIn("google", { callbackUrl: "/" })}
        />
      </main>
    </>
  );
}
