import { Button } from "@/components/BaseComponents/Button/Button";
import { NotesLayout } from "@/components_old/Layouts/NotesLayout";
import { api } from "@/utils/api";
import Head from "next/head";
import { useRouter } from "next/router";
import { MdKeyboardBackspace } from "react-icons/md";
import { FaRegEdit } from "react-icons/fa";
import Link from "next/link";

export default function NotesPage() {
  const {
    query: { id, listId },
  } = useRouter();
  const { data: note } = api.notes.getNoteById.useQuery(id as string);
  const router = useRouter();

  return (
    <>
      <Head>
        <title>notatka jedna</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NotesLayout>
        <main className="h-full w-full">
          <div className="align-center flex w-full justify-between">
            <Button
              type="button"
              icon={<MdKeyboardBackspace />}
              onClick={() => router.back()}
              style={{
                fontSize: "3rem",
                border: "none",
              }}
            />
            <Link
              href={{
                pathname: `/notes/${note?.id}/edit`,
                query: {
                  id: note?.id,
                  listId: listId,
                },
              }}
              as={`/notes/${note?.id}/edit`}
              style={{
                fontSize: "2.5rem",
              }}
            >
              <FaRegEdit />
            </Link>
          </div>
          <div>{note?.listId}</div>
          <div>{note?.title}</div>
          <div>{note?.text}</div>
        </main>
      </NotesLayout>
    </>
  );
}
