import { NotesList } from "@/components/NotesComponents/NotesList";
import Head from "next/head";

export default function LoginPage() {
  return (
    <>
      <Head>
        <title>notatki</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid h-full w-full grid-cols-3">
        <div className="flex h-full flex-col ">
          <NotesList />
          <NotesList />
          <NotesList />
        </div>
        <div className="col-span-2">select a note...</div>
      </main>
    </>
  );
}
