import { NotesList } from "@/components/NotesComponents/NotesList";
import { api } from "@/utils/api";
import Head from "next/head";

export default function NotesPage() {
  const { data: lists } = api.notes.getLists.useQuery();

  return (
    <>
      <Head>
        <title>notatki</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid h-full w-full grid-cols-3 p-4">
        <div className="flex h-full flex-col items-start">
          {lists?.map((list) => (
            <NotesList title={list.name} data={list.notes} key={list.id} />
          ))}
        </div>
        <div className="col-span-2">select a note...</div>
      </main>
    </>
  );
}
