import { AddNoteForm } from "@/components_old/Forms/AddNoteForm";
import { NotesLayout } from "@/components_old/Layouts/NotesLayout";
import { api } from "@/utils/api";
import { Note, User } from "@prisma/client";
import Head from "next/head";
import { useRouter } from "next/router";

export default function NotesPage() {
  const {
    query: { id },
  } = useRouter();
  const { data: note } = api.notes.getNoteById.useQuery(id as string);

  return (
    <>
      <Head>
        <title>notatka jedna</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NotesLayout>
        <main className="h-full w-full">
          <div>
            {note && (
              <AddNoteForm
                initialData={{
                  ...note,
                  sharedWith: note.sharedWith.map((el) => el.id),
                }}
              />
            )}
          </div>
          {note && (
            <div className="flex flex-col">
              <span>id: {note.id}</span>
              <span>title: {note.title}</span>
              <span>text: {note.text}</span>
              <span>listId: {note.listId}</span>
              <div>
                sharedWith:{" "}
                {note?.sharedWith.map((el) => <span key={el.id}>{el.id}</span>)}
              </div>
            </div>
          )}
        </main>
      </NotesLayout>
    </>
  );
}
