import { AddNoteForm } from "@/components/Forms/AddNoteForm";
import { NotesLayout } from "@/components/Layouts/NotesLayout";
import { api } from "@/utils/api";
import Head from "next/head";
import { useRouter } from "next/router";

export default function NotesPage() {
  const {
    query: { id },
  } = useRouter();
  const { data: note } = api.notes.getNoteById.useQuery(id as string);

  return (
    <>
      <Head>
        <title>notatka jedna</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NotesLayout>
        <main className="h-full w-full">
          {note && <AddNoteForm initialData={note} />}
        </main>
      </NotesLayout>
    </>
  );
}
