import { CustomCalendar } from "@/components_old/CustomCalendar/CustomCalendar";
import { Planer } from "@/components_old/Planer/Planer";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full w-full items-center ">
        <div className="w-1/5"></div>
        <div className="grid h-full w-full grid-cols-2 grid-rows-2 gap-5 p-5">
          <div className="rounded-2xl border-2">notatki</div>
          <div className="rounded-2xl border-2">jakieś rzeczy</div>
          <Planer />
        </div>
      </main>
    </>
  );
}
