import { AddNoteForm } from "@/components/Forms/AddNoteForm";
import { NotesLayout } from "@/components/Layouts/NotesLayout";
import Head from "next/head";

export default function AddNotePage() {
  return (
    <>
      <Head>
        <title>dodaj notatkę</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NotesLayout>
        <main className="h-full w-full">
          <div
            className="fixed left-1/2 top-1/2 h-1/2 w-1/2 -translate-x-1/2 -translate-y-1/2 rounded-3xl px-12 py-14 pb-5"
            style={{
              background: "rgba(255, 255, 255, .2)",
              backdropFilter: "blur(4px)",
            }}
          >
            <AddNoteForm />
          </div>
        </main>
      </NotesLayout>
    </>
  );
}
