import { AddNoteForm } from "@/components_old/Forms/AddNoteForm";
import { NotesLayout } from "@/components_old/Layouts/NotesLayout";
import Head from "next/head";

export default function AddNotePage() {
  return (
    <>
      <Head>
        <title>dodaj notatkę</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NotesLayout>
        <main className="h-full w-full">
          <div
            className="fixed left-1/2 top-1/2 z-20 h-1/2 w-1/2 -translate-x-1/2 -translate-y-1/2 rounded-3xl border-2 p-4"
            style={{ background: "var(--primary-bg)" }}
          >
            <AddNoteForm />
          </div>
          <div
            className="fixed left-0 top-0 z-10 h-full w-full"
            style={{
              background: "rgba(70, 80, 55, 0.2)",
              backdropFilter: "blur(4px)",
            }}
          />
        </main>
      </NotesLayout>
    </>
  );
}
